// Breaking the proxy on purpose, to show the suite would notice.
//
// A leak test that has never seen a leak is a test that passes. The assertions
// in #132 all say "the credential is not here", and every one of them would go
// on passing if the canary were never planted, if the tool never ran, or if the
// scan looked at the wrong object. The positive control in canary.ts covers the
// first two. This covers the third: neuter the proxy's redaction pass, run the
// same scenario, and require the suite to fail.
//
// **Why a loader hook and not a stub.** The proxy is a separate operating-system
// process — deliberately, since that boundary is what the leak claim is about —
// so nothing in the test process can reach inside it. Its imports are ESM
// bindings, which are read-only even from within: `import { redactSecrets }`
// cannot be reassigned by anything. What the harness *does* control is how the
// process is launched, so the mutation goes in as a `--import` hook that rewrites
// the module's source as Node loads it.
//
// **It patches compiled output, and that is the cost.** The needle below is a
// line of `packages/proxy/dist/redact.js`, so a refactor of `redactSecrets` can
// invalidate it. That is inherent to reaching into another process rather than
// sloppiness — and the hook throws when the needle misses, so the failure is
// "the mutation did not apply" rather than a green test that mutated nothing.

import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { Cleanup } from "./cleanup.js";

/**
 * The line `redactSecrets` opens with, and the early return that guts it.
 *
 * Turning the function into the identity rather than deleting the call site:
 * everything else — the choke point in `callUpstream`, the header allowlist, the
 * one return — stays exactly as shipped, so what the mutant proves is that the
 * *scrub* is what stops the leak, and not some other part of the path.
 */
const NEEDLE = "let out = text;";
const REPLACEMENT = "let out = text; return out;";

/**
 * Writes a loader hook and returns its path, for `startRig({ nodeArgs })`.
 *
 * ```ts
 * const rig = await startRig({
 *   nodeArgs: ["--import", breakRedaction(cleanup)],
 *   upstream: { echoHeaders: "text" }
 * });
 * ```
 *
 * The hook is scoped to the one spawned process and touches no build output on
 * disk, so a mutant case cannot leak into the run that follows it.
 */
export function breakRedaction(cleanup: Cleanup): string {
  return writeHook(cleanup, {
    file: "break-redaction.mjs",
    module: "/proxy/dist/redact.js",
    needle: NEEDLE,
    replacement: REPLACEMENT,
    missed: "redactSecrets no longer opens with"
  });
}

/**
 * The line `injectCredential` opens with, and the early return that guts it.
 *
 * The identity again rather than a deleted call site, and the choice carries
 * more here: gutting the *mint* instead would fail the call outright — no
 * request reaches the upstream and every assertion fails together. With only
 * the header's attachment removed, the whole token path stays as shipped — the
 * grant is read, the exchange runs, the rotation persists, the call goes out —
 * and the one assertion that fails is the positive control, which is exactly
 * the claim #258 makes about it.
 */
const INJECT_NEEDLE = "export function injectCredential(headers, scheme, value) {";
const INJECT_REPLACEMENT = `${INJECT_NEEDLE}\n    return { ...headers };`;

/**
 * Writes a loader hook that sends every outbound call out bare, for
 * `startRig({ nodeArgs })` — the token path's mutant, per `breakRedaction`.
 */
export function breakCredentialInjection(cleanup: Cleanup): string {
  return writeHook(cleanup, {
    file: "break-injection.mjs",
    module: "/proxy/dist/outbound.js",
    needle: INJECT_NEEDLE,
    replacement: INJECT_REPLACEMENT,
    missed: "injectCredential no longer opens with"
  });
}

function writeHook(
  cleanup: Cleanup,
  hook: { file: string; module: string; needle: string; replacement: string; missed: string }
): string {
  const dir = mkdtempSync(join(tmpdir(), "libero-e2e-mutate-"));
  cleanup.add("mutation hook", () => rmSync(dir, { recursive: true, force: true }));

  const file = join(dir, hook.file);
  writeFileSync(
    file,
    `// Generated by e2e/src/harness/mutate.ts. Runs inside the spawned proxy.
import { registerHooks } from "node:module";

registerHooks({
  load(url, context, nextLoad) {
    const loaded = nextLoad(url, context);
    if (!url.endsWith(${JSON.stringify(hook.module)})) return loaded;

    const source = loaded.source.toString();
    const broken = source.replace(${JSON.stringify(hook.needle)}, ${JSON.stringify(hook.replacement)});
    // Loud, and before the proxy serves anything. A hook that silently matched
    // nothing would leave the mutant case asserting against unmutated code and
    // reporting that as a pass — the exact failure this file exists to prevent.
    if (broken === source) {
      throw new Error("e2e: the mutation did not apply — " + ${JSON.stringify(hook.missed)} + " " + ${JSON.stringify(
        hook.needle
      )});
    }
    return { ...loaded, source: broken };
  }
});
`,
    "utf8"
  );
  return file;
}
