// Breaking the proxy on purpose, to show the suite would notice.
//
// A leak test that has never seen a leak is a test that passes. The assertions
// in #132 all say "the credential is not here", and every one of them would go
// on passing if the canary were never planted, if the tool never ran, or if the
// scan looked at the wrong object. The positive control in canary.ts covers the
// first two. This covers the third: neuter the proxy's redaction pass, run the
// same scenario, and require the suite to fail.
//
// **Why a loader hook and not a stub.** The proxy is a separate operating-system
// process — deliberately, since that boundary is what the leak claim is about —
// so nothing in the test process can reach inside it. Its imports are ESM
// bindings, which are read-only even from within: `import { redactSecrets }`
// cannot be reassigned by anything. What the harness *does* control is how the
// process is launched, so the mutation goes in as a `--import` hook that rewrites
// the module's source as Node loads it.
//
// **It patches compiled output, and that is the cost.** The needle below is a
// line of `packages/proxy/dist/redact.js`, so a refactor of `redactSecrets` can
// invalidate it. That is inherent to reaching into another process rather than
// sloppiness — and the hook throws when the needle misses, so the failure is
// "the mutation did not apply" rather than a green test that mutated nothing.

import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { Cleanup } from "./cleanup.js";

/**
 * The line `redactSecrets` opens with, and the early return that guts it.
 *
 * Turning the function into the identity rather than deleting the call site:
 * everything else — the choke point in `callUpstream`, the header allowlist, the
 * one return — stays exactly as shipped, so what the mutant proves is that the
 * *scrub* is what stops the leak, and not some other part of the path.
 */
const NEEDLE = "let out = text;";
const REPLACEMENT = "let out = text; return out;";

/**
 * Writes a loader hook and returns its path, for `startRig({ nodeArgs })`.
 *
 * ```ts
 * const rig = await startRig({
 *   nodeArgs: ["--import", breakRedaction(cleanup)],
 *   upstream: { echoHeaders: "text" }
 * });
 * ```
 *
 * The hook is scoped to the one spawned process and touches no build output on
 * disk, so a mutant case cannot leak into the run that follows it.
 */
export function breakRedaction(cleanup: Cleanup): string {
  const dir = mkdtempSync(join(tmpdir(), "libero-e2e-mutate-"));
  cleanup.add("mutation hook", () => rmSync(dir, { recursive: true, force: true }));

  const file = join(dir, "break-redaction.mjs");
  writeFileSync(
    file,
    `// Generated by e2e/src/harness/mutate.ts. Runs inside the spawned proxy.
import { registerHooks } from "node:module";

registerHooks({
  load(url, context, nextLoad) {
    const loaded = nextLoad(url, context);
    if (!url.endsWith("/proxy/dist/redact.js")) return loaded;

    const source = loaded.source.toString();
    const broken = source.replace(${JSON.stringify(NEEDLE)}, ${JSON.stringify(REPLACEMENT)});
    // Loud, and before the proxy serves anything. A hook that silently matched
    // nothing would leave the mutant case asserting against unmutated code and
    // reporting that as a pass — the exact failure this file exists to prevent.
    if (broken === source) {
      throw new Error("e2e: the redaction mutation did not apply — redactSecrets no longer opens with " + ${JSON.stringify(
        NEEDLE
      )});
    }
    return { ...loaded, source: broken };
  }
});
`,
    "utf8"
  );
  return file;
}
