// What a turn cost, told to the proxy's budget meter over the same mutual-TLS
// connection a tool call takes.
//
// The proxy meters tool calls from calls it served, and needs nobody's
// cooperation to count those. Tokens are different: only the process that
// talked to the model knows what a turn cost, so it says so, and without this
// the meter's token counter reads zero however much a channel spends.
//
// **This is not the model being asked what it cost.** The counts are parsed out
// of the provider's HTTP response envelope — `toUsage()` in
// ../completion/anthropic.ts reads `message.usage` — and a prompt-injected
// model emits text, which has no reach into the envelope its own tokens are
// counted in. Forging a report needs the agent *process*, which is a compromise
// the security model already states as an assumption whose consequences are
// larger than an under-reported token count.
//
// **Pinned to one channel at construction**, exactly as the tool client is: the
// channel is not a parameter on `report`, so there is no report this object can
// send that a different certificate would authenticate. And no `channel` in the
// body, and none possible — `SpendReport` is strict, so a body carrying one is
// rejected rather than having the field quietly dropped. The day is not in the
// body either; the proxy stamps its own clock.
//
// **Four raw counts, never a total.** What a cached token costs is the
// channel's team sheet's answer, applied where the budget is, so an operator
// changes it with a sheet edit rather than an agent release. A total sent from
// here would move that decision into this process.
//
// **No `AbortSignal` parameter, deliberately.** The only signal in scope is the
// one that cancels a task, and a cancelled task still spent tokens — handing it
// here would mean shutdown deliberately discarding a real count. This object
// carries its own deadline instead, short because the person waiting for their
// answer is waiting behind it.
//
// **A failed report throws, and swallowing it is the caller's.** A meter that
// cannot be reached costs an operator a counter; it must not cost a user their
// reply. That is policy, and it lives where the logger does — this file has no
// way to log and should not gain one.

import { SpendReportResponse, type SpendReport } from "@getlibero/schema";
import type { TokenUsage } from "../completion/types.js";
import { proxyErrorFrom } from "./errors.js";
import { ProxyClientError, type ProxyTransport } from "./transport.js";

/**
 * How long a report may take before it is abandoned.
 *
 * An order of magnitude under the transport's own default, because the two
 * deadlines protect different things. A tool call's deadline is how long the
 * model may wait on work the proxy is doing for it. This one is how long a
 * Slack thread waits on bookkeeping nobody asked for: the proxy's work is one
 * parse and one row, and a meter that has not answered in five seconds is not
 * going to answer usefully.
 */
export const DEFAULT_SPEND_TIMEOUT_MS = 5_000;

export interface ProxySpendClientOptions {
  transport: ProxyTransport;
  /** Whose certificate every report presents. Fixed for the life of this object. */
  channel: string;
  timeoutMs?: number;
}

/**
 * Whether the report moved the meter.
 *
 * `duplicate` is a success, not a warning: it is the right answer to a retry
 * under a turn id already counted, and the reason a retry is safe at all.
 */
export type SpendOutcome = SpendReportResponse["outcome"];

export interface ProxySpendClient {
  /**
   * One turn's spend.
   *
   * `turn` is the idempotency key and must satisfy `TurnId` in
   * @getlibero/schema. Generated by this process and never by the model —
   * `AgentTaskResult.taskId` is a UUID and satisfies it.
   *
   * `model` is the id the provider echoed back (#62), already checked against
   * `ModelId` by the adapter that read it — this object does not validate it,
   * for the same reason it does not validate the counts. Omitted when the
   * provider echoed none, which is a report the proxy accepts and meters under
   * a bucket it cannot price.
   *
   * `costNanoUsd` is what a router said the same call cost (#239), already
   * bounded by the adapter that read the header. Omitted when nothing reported
   * one, which is every direct provider call — the proxy records a comparison
   * for the calls that carry one and meters every call the same either way.
   */
  report(
    turn: string,
    usage: TokenUsage,
    model?: string,
    costNanoUsd?: number
  ): Promise<SpendOutcome>;
}

export function createProxySpendClient(options: ProxySpendClientOptions): ProxySpendClient {
  const { transport, channel } = options;
  const timeoutMs = options.timeoutMs ?? DEFAULT_SPEND_TIMEOUT_MS;

  return {
    async report(
      turn: string,
      usage: TokenUsage,
      model?: string,
      costNanoUsd?: number
    ): Promise<SpendOutcome> {
      // Typed as the wire shape on purpose: after the schema's defaults, all
      // four counts are required, so a usage object missing one does not
      // compile rather than arriving as a silent zero the meter cannot tell
      // from a real one.
      const body: SpendReport = {
        turn,
        // The key is omitted rather than sent as null when there is no model.
        // The schema is strict and the field is optional, so an explicit null
        // is a 400 — which would lose this turn's counts over a field that was
        // only ever going to be absent.
        ...(model === undefined ? {} : { model }),
        usage: {
          inputTokens: usage.inputTokens,
          outputTokens: usage.outputTokens,
          // Absent means the provider never mentioned them, which means they
          // were not spent. The loop keeps "not reported" and "zero" apart
          // because a cap has to know which it is looking at; a meter column
          // cannot hold the difference and does not need to.
          cacheReadInputTokens: usage.cacheReadInputTokens ?? 0,
          cacheCreationInputTokens: usage.cacheCreationInputTokens ?? 0
        },
        // Omitted rather than sent as null, for the reason `model` is — and
        // with more at stake, because this field is the newer of the two: an
        // explicit null is a 400 on a strict schema, and a 400 costs the turn
        // its counts over a second opinion nothing enforces on.
        ...(costNanoUsd === undefined ? {} : { costNanoUsd })
      };

      // Not parsed here before sending. The proxy's parse at its own edge is
      // the authority, and a second opinion in this process either agrees — in
      // which case it is dead code that can drift — or disagrees, in which case
      // the shape is decided by the wrong end. A bad count comes back as a 400,
      // which is visible on both sides.
      const deadline = AbortSignal.timeout(timeoutMs);
      let response;
      try {
        response = await transport.request({
          channel,
          method: "POST",
          path: "/v1/spend",
          body,
          signal: deadline
        });
      } catch (cause) {
        // The transport reports any aborted signal as a cancellation, which is
        // right when a caller cancelled and wrong here: this object takes no
        // caller signal, so the only thing that can have aborted is the
        // deadline above. Said as what it is, or an operator reads "cancelled"
        // as "the process was shutting down" and goes looking for a shutdown.
        if (cause instanceof ProxyClientError && cause.reason === "cancelled" && deadline.aborted) {
          throw new ProxyClientError("proxy client: the spend report timed out", "timed_out");
        }
        throw cause;
      }

      if (response.status !== 200) throw proxyErrorFrom(response.body, "the spend report failed", response.status);

      const parsed = SpendReportResponse.safeParse(response.body);
      if (!parsed.success) {
        throw new ProxyClientError(
          "proxy client: the spend report answer was not a valid response",
          "malformed_response"
        );
      }

      return parsed.data.outcome;
    }
  };
}
